const colors = {
  light: {
    text: "#1A1A2E",
    tint: "#E94560",
    background: "#F0F4FF",
    foreground: "#1A1A2E",
    card: "#FFFFFF",
    cardForeground: "#1A1A2E",
    primary: "#E94560",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF2FF",
    secondaryForeground: "#1A1A2E",
    muted: "#EEF2FF",
    mutedForeground: "#5A6480",
    accent: "#F5A623",
    accentForeground: "#1A1A2E",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#D0D8F0",
    input: "#D0D8F0",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#E94560",
    background: "#1A1A2E",
    foreground: "#FFFFFF",
    card: "#16213E",
    cardForeground: "#FFFFFF",
    primary: "#E94560",
    primaryForeground: "#FFFFFF",
    secondary: "#0F3460",
    secondaryForeground: "#FFFFFF",
    muted: "#0F3460",
    mutedForeground: "#8892A4",
    accent: "#F5A623",
    accentForeground: "#1A1A2E",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1E2A45",
    input: "#1E2A45",
  },
  radius: 14,
};

export default colors;
